module.exports = {
    "login": "ASASCED",
    "id": 18502412,
    "node_id": "MDQ6VXNlcjE4NTAyNDEy",
    "avatar_url": "https://avatars1.githubusercontent.com/u/18502412?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/ASASCED",
    "html_url": "https://github.com/ASASCED",
    "followers_url": "https://api.github.com/users/ASASCED/followers",
    "following_url": "https://api.github.com/users/ASASCED/following{/other_user}",
    "gists_url": "https://api.github.com/users/ASASCED/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/ASASCED/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/ASASCED/subscriptions",
    "organizations_url": "https://api.github.com/users/ASASCED/orgs",
    "repos_url": "https://api.github.com/users/ASASCED/repos",
    "events_url": "https://api.github.com/users/ASASCED/events{/privacy}",
    "received_events_url": "https://api.github.com/users/ASASCED/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Jesús Jiménez",
    "company": null,
    "blog": "",
    "location": null,
    "email": null,
    "hireable": null,
    "bio": "I´m a programmer with experience in Java and Develop WEB",
    "public_repos": 9,
    "public_gists": 0,
    "followers": 0,
    "following": 0,
    "created_at": "2016-04-16T15:08:10Z",
    "updated_at": "2019-08-31T03:42:03Z"
}